### ISSUE TITLE
Última mudança em mergesed2 não funciona na minha máquina

### ISSUE THREAD

**Issue by vieirarg** [danmoser/pyhdust#20]
Mudança 'Upd' feita em 20 de junho de 2018 não funciona na minha máquina (linux mint). A versão anterior que eu havia publicado (15 de junho de 2018) estava funcionando. Pelo que entendi, o Moser reverteu a alteração por uma incompatibilidade de sistema operacional. Como só sei o que funciona na minha máquina, e para evitar ficar "indo e voltando" com essas mudanças, vou trabalhar no momento com uma versão local da rotina (fora do git). Mas o ideal seria convergirmos para uma versão única, podemos discutir isso depois...

**Comment by danmoser** [comment]
Rodrigo,
Vc me manda o erro?

**Comment by vieirarg** [comment]
In [2]: phd.mergesed2(models, Vrots, path=None, checklineval=False, onlyfilters=None)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-2-1e15148dce36> in <module>()
----> 1 phd.mergesed2(models, Vrots, path=None, checklineval=False, onlyfilters=None)

/home/vieira/Dropbox/python/pyhdust/pyhdust/__init__.pyc in mergesed2(models, Vrots, path, checklineval, onlyfilters)
    506         if onlyfilters is None:
    507             lsed2 = _glob(_os.path.join('{0}'.format(modfld), 
--> 508                 '*{1}.sed2'.format(modelname[:-4])))
    509             lsed2.extend( _glob(_os.path.join('{0}'.format(modfld), 
    510                 '*{1}_SEI.sed2'.format(modelname[:-4]))) )

IndexError: tuple index out of range

In [3]:

**Comment by danmoser** [comment]
O problema é a falta do ``list``... Vou atualizar e vc testa pf

**Comment by vieirarg** [comment]
Blz Moser, valeu!

**Comment by danmoser** [comment]
Teste aí. Se funcionar, pode fechar o issue :-)

**Comment by vieirarg** [comment]
Sucesso Daniel, funcionando! Valeu
