### ISSUE TITLE
Error in __init__.py with plottemp

### ISSUE THREAD

**Issue by ghost** [danmoser/pyhdust#21]
When trying to run plottemp in python3, on line 1075 of \_\_init\_\_.py an error is returned

> IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

I solved this by adding in an additional "/" character to make is as follows:

`y = data[3 + lev, :, ncmu // 2 + np + rplus, icphi]`

I believe the issue lied in looking for an index which was a float, but by adding in the extra "/" character the value is converted to an int directly.

I hope this helps!

**Comment by vieirarg** [comment]
Hi Keegan,
Thanks for your warning, and proposed solution. I have just implemented it, please update your pyhdust local version. I am closing the issue now.
