### ISSUE TITLE
__init__ Warning Line 39 Missing astropy from list of modules that need to be installed

### ISSUE THREAD

**Issue by whatamithinking** [danmoser/pyhdust#35]
Hey...I am just using your lib for color conversions, but I keep getting a user warning:

# matplotlib, pyfits, six and/or scipy module not installed!!

This is from line 39 of your init file. I checked and all of those are installed. But your try/except includes astropy, which is not mentioned in the above warning:

try:
    import matplotlib.pyplot as _plt
    import matplotlib.patches as _mpatches
    from scipy import interpolate as _interpolate
    from scipy.interpolate import griddata as _griddata
    import astropy.io.fits as _pf
except ImportError:
    _warn.warn('# matplotlib, pyfits, six and/or scipy module not installed!!')

Could you please update the warning to include all the libraries you are actually checking for?

**Comment by danmoser** [comment]
Dear Connor,
Thank you very much for your feedback!
Indeed _pyfits_ is deprecated, _six_ is a mandatory package, and _astropy_ was not mentioned. I'm publishing the version v1.3.18 with the correction right now.
